[package]
name = "tokio-sqlite"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
description = "Asynchronous SQLite client"
keywords = ["tokio", "sqlite"]

[dependencies]
rusqlite = "0.30.0"
tokio = { version = "1.35.1", features = ["sync", "rt-multi-thread"] }

[dev-dependencies]
rand = "0.8.5"
tokio = { version = "1.35.1", features = ["macros"] }
